"""empty message

Revision ID: d7a40b9b7cdc
Revises: d2e6d13e6da8
Create Date: 2024-09-16 01:46:29.831613

"""

from alembic import op
import sqlalchemy as sa

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = "d7a40b9b7cdc"
down_revision = "d2e6d13e6da8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifax", schema=None) as batch_op:
        batch_op.alter_column(
            "image",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=1000),
            existing_nullable=False,
        )

    if environment == "production":
        op.execute(f"ALTER TABLE artifax SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifax", schema=None) as batch_op:
        batch_op.alter_column(
            "image",
            existing_type=sa.String(length=1000),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
